   # Topic 02: Numpy Array Creation

In [36]:
import numpy as np   ##1.Creating an array from a list:
my_list = [5,10,15,20,25,30]
a = np.array(my_list)
print(a)


[ 5 10 15 20 25 30]


In [37]:
import numpy as np    ##1.Creating an array from a tuple:
my_tuple = (2,4,6,8,10)
a = np.array( my_tuple)
print(a)

[ 2  4  6  8 10]


In [ ]:
        ##Creating an array of zeros or ones:

In [7]:
a = np.zeros(9)  ##Example 01
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
a = np.zeros((7, 4))   ##Example 02:
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a = np.ones(3)    ##Example 03:
print(a)

[1. 1. 1.]


In [17]:
a = np.ones((6, 9))    ##Example 04:
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [25]:
a = np.arange(0, 80, 8)    ##3.Creating an array with a range of values:
print(a)

[ 0  8 16 24 32 40 48 56 64 72]


In [34]:
a = np.random.rand(2,6) ##Creating an array of random values:
print(a)

[[0.59704663 0.78381099 0.57726946 0.95551073 0.53835022 0.02738094]
 [0.71998537 0.94251844 0.54593553 0.64128936 0.46372718 0.38463273]]


In [2]:
import numpy as np
a = np.linspace(0, 0.5, 20)  ##Creating an array of evenly spaced values:
print(a)

[0.         0.02631579 0.05263158 0.07894737 0.10526316 0.13157895
 0.15789474 0.18421053 0.21052632 0.23684211 0.26315789 0.28947368
 0.31578947 0.34210526 0.36842105 0.39473684 0.42105263 0.44736842
 0.47368421 0.5       ]
