   # Topic= NumPy Array Slicing:

In [ ]:
  ## Slicing 1-D Array

In [31]:
import numpy as np             ##Simple Slicing
a = np.array([10,20,30,40,50,60,70,80,90,100])
print("Output Slicing:",a[3:8])

Output Slicing: [40 50 60 70 80]


In [32]:
a = np.array([11,12,13,14,15,16,17,18])  ##Example 02
print("Output Slicing:",a[5:])

Output Slicing: [16 17 18]


In [34]:
a = np.array([10,12,14,16,18,20,22,24,26])  ##Example 03
print("Output Slicing:",a[:7])

Output Slicing: [10 12 14 16 18 20 22]


In [18]:
  ## Negative Slicing
a= np.array([1,2,3,4,5,6,7,8])   ##Example 01
print("Output Slicing:",a[-5:-1])

Output Slicing: [4 5 6 7]


In [38]:
a= np.array([1,2,3,4,5,6,7,8])   ##Example 02
print("Output Slicing:",a[:-6,])

Output Slicing: [1 2]


In [20]:
a= np.array([1,2,3,4,5,6,7,8])   ##Example 03
print("Output Slicing:",a[-6:])

Output Slicing: [3 4 5 6 7 8]


In [40]:
  ## Step Slicing
a = np.array([10,11,12,13,14,15,16,17,18])  ##Example 01
print("Output Slicing:",a[1:8:3])

Output Slicing: [11 14 17]


In [41]:
a = np.array([1,2,3,4,5,6,7,8,9,10])  ##Example 02
print("Output Slicing:",a[6::])

Output Slicing: [ 7  8  9 10]


In [43]:
a = np.array([1,2,3,4,5,6,7,8,9,10])  ##Example 03
print("Output Slicing:",a[::2])

Output Slicing: [1 3 5 7 9]


In [44]:
  ## Slicing 2-D Arrays
import numpy as np               ##Example 01
a = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])
print("Output Slicing:",a[0, 1:4])

Output Slicing: [20 30 40]


In [47]:
a = np.array([[23, 42, 63, 76, 85], [61, 47, 98, 39, 10]])      ##Example 02
print("Output Slicing:",a[0:2,3])

Output Slicing: [76 39]


In [49]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])      ##Example 03
print("Output Slicing:",a[0:3,3])

Output Slicing: [4 9]


In [50]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])      ##Example 04
print("Output Slicing:",a[0:2, 1:4])

Output Slicing: [[2 3 4]
 [7 8 9]]


In [51]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
print("Output Slicing:", a[0:2, 2])

Output Slicing: [3 7]


In [52]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
print("Input Array:",a)
print()
print("Output Slicing:", a[0:3, 1:])

Input Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

Output Slicing: [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
